POST http://localhost:8080/users/
Content-Type: application/json

{
  "id": "firstId",
  "username": "FirstUser",
  "email": "FirstUser@example.com"
}

###
GET http://localhost:8080/users/
Accept: application/json

###
